### ISSUE TITLE
Timeshift fails to write on smb share

### ISSUE THREAD

**Issue by puenktchen** [xbmc/inputstream.ffmpegdirect#60] opened 2020-07-05 23:48 UTC
IPTV Simple PVR addon Timeshifting doesn't work if the timeshifting folder is an smb share.
I'm using the same smb share as a source for timeshifting within the DVBViewer PVR addon, so it can't be a permission problem.
If you look at the log, it's not clear if Kodi sanitizes the smb user and password in the log or if ffmpegdirect just don't use it.
Sometimes it's this:
`smb://USERNAME:PASSWORD@192.168.0.2/Timeshift/221516196-00000001.seg`
And other times it's that (i've sanitized it myself):
`smb://myuser:mypassword@192.168.0.2/Timeshift//221516196-00000001.seg`
Also there's a second slash after "Timeshift". Maybe just a fault in ffmpegdirect logging.

If i run Kodi directly on the server, then timeshifting to smb is working. But then of course Kodi runs under the user account context, so credentials for the smb share aren't needed.

Debug log: https://paste.kodi.tv/pevohataza.kodi

**Comment by phunkyfish** [comment] 2020-07-06 07:27
If you use the SMB share with no password does it work?

Is the SMB share configured as a source in kodi or is it configured some other way?

I can try checking for a slash before appending the file name to see if that works. Maybe SMB is unique in this regard.

**Comment by phunkyfish** [comment] 2020-07-06 10:11
I'll be honest. I never considered that a username/password would be embedded in the URL. I had assumed that any SMB details would be part of the source configuration in kodi.

Anything logged by the addon will not sanitise anything in the URL. That is a function of kodi and not the addon. The ones that are sanitised are calls made by kodi.

Can you try a testbuild from here, I have removed the trailing slash and it might make a difference (although I don't think that's the issue at all): https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.ffmpegdirect/detail/PR-59/3/artifacts

PR is here: https://github.com/xbmc/inputstream.ffmpegdirect/pull/59

**Comment by puenktchen** [comment] 2020-07-06 17:05
> If you use the SMB share with no password does it work?

The folder is already shared for "Everyone". I've even edited the NTFS permissions now to allow "Modifiy" for "Everyone. Doesn't help.
> Is the SMB share configured as a source in kodi or is it configured some other way?

Yes it's a Kodi source. It's in "mediasources.xml" with user and password. I've also created an entry in "passwords.xml" now. Nothing.
> Can you try a testbuild from here, I have removed the trailing slash and it might make a difference (although I don't think that's the issue at all): https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.ffmpegdirect/detail/PR-59/3/artifacts

No difference. The error is always the same in the log files:
`SMBFile->Open: Unable to open file : 'smb://USERNAME:PASSWORD@192.168.0.2/Timeshift/819393947.idx'
unix_err:'2' error : 'No such file or directory'`

**Comment by phunkyfish** [comment] 2020-07-06 18:38
So you can’t configure kodi to not require a password for SMB?

@AlwinEsch should calling open file be ok for an SMB share with a username and password?

It’s possible this is an issue with the C++ api as I think your DVB viewer might still be using the C api.

**Comment by phunkyfish** [comment] 2020-07-06 18:44
Ok, it looks like your on the C++ API for dvbviewer. Let me compare dvbviewer and ffmpegdirect.

**Comment by emveepee** [comment] 2020-07-06 23:45
I tested without password on a cifs share  from windows and I didn't see any issue with writing to the share (Debian OMV)  "Everyone" is not the same as guest though so perhaps that is the issue.

While looking into this I did notice that the open seq file was not being deleted 
```
2020-07-06 19:32:11.283 T:22308   DEBUG <general>: XFILE::CWin32SMBDirectory::ConnectAndAuthenticate: Connected to "\\172.16.3.244\videos" without username and without password
2020-07-06 19:32:11.287 T:22308   ERROR <general>: XFILE::CFile::Delete - Error deleting file smb://172.16.3.244/videos/timeshift/143428246-00000000.seg
```
That seems to be because ~TimeshiftBuffer() is called before ~TimeshiftSegment() so the current file was open

I added  m_writeSegment->MarkAsComplete(); to ~TimeshiftBuffer() which closes the file and I didn't get that error and the file is deleted.   

linux filesystem let you delete open files which might explain why this hasn't been mentioned.

**Comment by puenktchen** [comment] 2020-07-07 01:15
> So you can’t configure kodi to not require a password for SMB?

I've tried it now with a share that doesn't require a password. Nothing.
Will try it later today from a Windows Laptop to my Windows Server. 
> It’s possible this is an issue with the C++ api as I think your DVB viewer might still be using the C api.

The last time it was working with DVBViewer. But that is a month ago. Now the DVBViewer pvr addon is completely broken.

**Comment by phunkyfish** [comment] 2020-07-07 06:57
Ok. There is someone looking at the dvbviewer addon. Although that does mean that it could be the C++ API as the last version you would have used would have had the C API.

**Comment by phunkyfish** [comment] 2020-07-07 10:22
> 
> That seems to be because ~TimeshiftBuffer() is called before ~TimeshiftSegment() so the current file was open
> 
> I added m_writeSegment->MarkAsComplete(); to ~TimeshiftBuffer() which closes the file and I didn't get that error and the file is deleted.
> 
> linux filesystem let you close open files which might explain why this hasn't been mentioned.

Nice, I will add this.

**Comment by puenktchen** [comment] 2020-07-07 18:24
Okay, i've tested now with a Windows 10 Laptop:
Without user credentials it works, ~~but when they are needed, it also fails.~~ <- also with. (was a conflict with existing credentials)

On Android it fails everytime, no matter if credentials are needed or not.

**Comment by phunkyfish** [comment] 2020-07-07 20:51
Ok, so the issue is Android only?

**Comment by puenktchen** [comment] 2020-07-07 21:18
> Ok, so the issue is Android only?

It seems so.

**Comment by phunkyfish** [comment] 2020-07-07 21:23
Can you browse the SMB share directly on the android os? I.e. not from kodi.

**Comment by puenktchen** [comment] 2020-07-07 21:40
> Can you browse the SMB share directly on the android os? I.e. not from kodi.

Android has no integrated file browser, but if you mean within an other Playstore app like "X-plore", then yes.
I can also mount the share as a storage to the Nvidia Shield, but unfortunately those storage mount point don't show up in Kodi.
The media source in Kodi that i've created from the share can be used in Kodi's filemanager to copy local files from the Android device to the server.

**Comment by emveepee** [comment] 2020-07-07 22:06
I see the same thing on Android.  I add the password protected share as a source and I can browse the folder and play files in the libraries via Android so I know I have access.   

Here is an audit log from my OMV Debian NAS  .219 is my Windows box, .111 is my Android box.  I don't know what those /1 files that are being unlinked are but I am not seeing anything else

![image](https://user-images.githubusercontent.com/2148031/86848582-41c30900-c07c-11ea-9c55-0cd0a393d608.png)

**Comment by phunkyfish** [comment] 2020-07-07 22:47
Strange. This must be a virtual file system issue with addons only on android.

@AlwinEsch any ideas?

**Comment by emveepee** [comment] 2020-07-08 15:06
I noticed that runner.py was able to access the share for deleting so I added a test

```
try:
    f = xbmcvfs.File(timeshiftBufferPath + 'Android.txt', 'w')
    f.write('hello world')
    f.close()
except Exception as err:
    xbmc.log(str(err), xbmc.LOGINFO )
```

which works so the Kodi vfs can write to the share from python on Android.    

@AlwinEsch if there is a change coming I would like an option to OpenFileForWrite() that doesn't silently create folders.

**Comment by puenktchen** [comment] 2020-07-12 00:06
Just a note: if i define a timeshift path to a folder inside the share and the folder is missing at playback start,
then the folder is created like expected. So it's really not a permission issue.

@phunkyfish can you do me a favour and create a new test build with the bool file overwrite "true" at this line:
https://github.com/xbmc/inputstream.ffmpegdirect/blob/99b42738d6efacc559ebc5963ec6e8f995b263fc/src/stream/TimeshiftBuffer.cpp#L61

I have a hard time to understand C/C++ but for me it looks like the missing **overwrite** parameter just returns false for a CFile.
OpenFileForWrite in Filesystem.cpp and File.cpp hasn't changed since years, but **overwrite** "true" is what DVBViewer is using.
I know it doesn't make sense, because why should it be needed on one OS but not the other. But it should not harm and Alwin seems to be on vacation.

**Comment by emveepee** [comment] 2020-07-13 03:31
I had a chance to compile this and the true did seem to make a difference on Android.  I didn't think it was creating the idx but that just was needed a .Flush() so I could see it.

There was a lot of buffering though and my Android box was running wired so it might not be as useful as I hoped.  Also each device will need it's own folder or you could erase other devices' files.

```
2020-07-12 22:55:27.769 T:6771    DEBUG <general>: AddOnLog: inputstream.ffmpegdirect: CDVDDemuxFFmpeg::AddStream ID: 0
2020-07-12 22:55:27.769 T:6771    DEBUG <general>: AddOnLog: inputstream.ffmpegdirect: CDVDDemuxFFmpeg::AddStream ID: 1
2020-07-12 22:55:27.769 T:6771    DEBUG <general>: AddOnLog: inputstream.ffmpegdirect: Start - Timeshift: started
2020-07-12 22:55:27.769 T:6771  WARNING <general>: SMBFile::OpenForWrite() called with overwriting enabled! - smb://USERNAME:PASSWORD@172.16.3.244/kodi/timeshift/752174000.idx
2020-07-12 22:55:27.775 T:6771    DEBUG <general>: AddOnLog: inputstream.ffmpegdirect: TimeshiftSegment - Segment ID: 0, Segment Filename: 752174000-00000000.seg
2020-07-12 22:55:27.779 T:6771  WARNING <general>: SMBFile::OpenForWrite() called with overwriting enabled! - smb://USERNAME:PASSWORD@172.16.3.244/kodi/timeshift/752174000-00000000.seg
2020-07-12 22:55:27.786 T:6771    DEBUG <general>: AddOnLog: inputstream.ffmpegdirect: GetCapabilities()
2020-07-12 22:55:27.786 T:6777    DEBUG <general>: AddOnLog: inputstream.ffmpegdirect: DoReadWrite - Timeshift: started
2020-07-12 22:55:27.786 T:6777    DEBUG <general>: AddOnLog: inputstream.ffmpegdirect: AddPacket - Writing first segment - PTS: 4166.666667, DTA: 4166.666667, pts sec: 0.004167, dts sec: 0.004167
2020-07-12 22:55:27.795 T:6771     INFO <general>: Creating Demuxer
2020-07-12 22:55:27.795 T:6771    DEBUG <general>: AddOnLog: inputstream.ffmpegdirect: GetStreamIds()

```

**Comment by phunkyfish** [comment] 2020-07-13 10:19
@puenktchen here you go: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.ffmpegdirect/detail/PR-59/5/artifacts

I have to wonder why this is required though. I don't see why this is only needed on Android as logically it should never be needed.

**Comment by emveepee** [comment] 2020-07-13 13:28
> 
> I have to wonder why this is required though. I don't see why this is only needed on Android as logically it should never be needed.

Did you test on macos to a password protected share?    I will test ubuntu later today.  On posix I see this 

https://github.com/xbmc/xbmc/blob/master/xbmc/platform/posix/filesystem/SMBFile.cpp#L628

and then earlier in an commented out section https://github.com/xbmc/xbmc/blob/master/xbmc/platform/posix/filesystem/SMBFile.cpp#L417  indicates that the sbmc_open will return -1 on an password protected share.

Incidentily ffmpegdirect doesn't actually check for failures on OpenFileForWrites() for idx/seg which is another issue.

**Comment by puenktchen** [comment] 2020-07-13 17:24
> @puenktchen here you go: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.ffmpegdirect/detail/PR-59/5/artifacts

It's working!!! Beautiful! (And because the Shield has Gigabit LAN, there's also no buffering)
> I have to wonder why this is required though. I don't see why this is only needed on Android as logically it should never be needed.

So have we found a bug in Kodi?

**Comment by phunkyfish** [comment] 2020-07-13 21:43
> > I have to wonder why this is required though. I don't see why this is only needed on Android as logically it should never be needed.
> 
> So have we found a bug in Kodi?

Possibly. It seems to be something that should be cross platform that is not. It could also be a bug in ffmpeg direct.

**Comment by phunkyfish** [comment] 2020-07-13 21:58
> Incidentily ffmpegdirect doesn't actually check for failures on OpenFileForWrites() for idx/seg which is another issue.

How do you mean? The result for OpenFileForWrite is checked and logged for each occurrence.

**Comment by emveepee** [comment] 2020-07-13 22:58
> 
> How do you mean? The result for OpenFileForWrite is checked and logged for each occurrence.

Checked and logged yes but if it can't create them because of permissions or potentially disk space on a device like the SD card for an RPi, there is no safe exit.  Testing the smb logic Kodi crashed when I skipped when there is no real seg file to go to.

**Comment by phunkyfish** [comment] 2020-07-14 07:40
> > How do you mean? The result for OpenFileForWrite is checked and logged for each occurrence.
> 
> Checked and logged yes but if it can't create them because of permissions or potentially disk space on a device like the SD card for an RPi, there is no safe exit. Testing the smb logic Kodi crashed when I skipped when there is no real seg file to go to.

Fair, so it should exit the stream if it’s not possible to create. Question. Does this happen with a missing idx file? It should be ok when set files are missing. Or at least it was originally.

**Comment by phunkyfish** [comment] 2020-07-14 11:27
Ok, so latest version of PR should check if files exist and log disk space if possible. The stream won't start if the index file cannot be created.

@emveepee can you track if this avoids your crash scenario?

TestBuilds: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.ffmpegdirect/detail/PR-59/6/artifacts

**Comment by emveepee** [comment] 2020-07-14 14:17
It avoids the crash scenario on not being able to access but not on disk space.  I added a small 3MB quota to my share and see

```
-rw-rwxr--+ 1 mvallevand users       0 Jul 14 10:09 1486627829-00000006.seg
-rw-rwxr--+ 1 mvallevand users     180 Jul 14 10:09 1486627829.idx
-rw-rwxr--+ 1 mvallevand users       0 Jul 14 10:09 1486627829-00000005.seg
-rw-rwxr--+ 1 mvallevand users       0 Jul 14 10:08 1486627829-00000004.seg
-rw-rwxr--+ 1 mvallevand users  180224 Jul 14 10:08 1486627829-00000003.seg
-rw-rwxr--+ 1 mvallevand users  932660 Jul 14 10:08 1486627829-00000002.seg
-rw-rwxr--+ 1 mvallevand users  981085 Jul 14 10:08 1486627829-00000001.seg
-rw-rwxr--+ 1 mvallevand users 1030339 Jul 14 10:08 1486627829-00000000.seg
```

Once the disk is "full" playback continues but it crashes at seeks if LoadSegment() hits a 0 byte segment, and probably a partial segment too.

I also miss the anti-spam patch.

**Comment by phunkyfish** [comment] 2020-07-14 14:25
@emveepee Strange. So it creates 0 bytes files. I didn’t expect that. So it crashes on trying to read the first int value or does crash on trying to open the 0 byte file?

Ya, on the log stuff I need to redo that with a global/static variable. It turns out that ffmpeg can create a new thread which also logs and won’t have been initialised. Hence why I would not see log and you did.

**Comment by emveepee** [comment] 2020-07-14 14:41
It opens but  it is failing here https://github.com/phunkyfish/inputstream.ffmpegdirect/blob/lean-mode/src/stream/TimeshiftSegment.cpp#L381 because m_packetBuffer is short.   If it hits that short 180k segment I expect it could crash too.

**Comment by phunkyfish** [comment] 2020-07-14 17:40
> It opens but it is failing here https://github.com/phunkyfish/inputstream.ffmpegdirect/blob/lean-mode/src/stream/TimeshiftSegment.cpp#L381 because m_packetBuffer is short. If it hits that short 180k segment I expect it could crash too.

Ok, latest version should hopefully avoid the crash, can you check @emveepee? It should fix both the 0 byte and partial segment use cases.

The log spam should be fixed too.

Testbuilds: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.ffmpegdirect/detail/PR-59/7/artifacts

**Comment by emveepee** [comment] 2020-07-14 19:24
It didn''t crash when skipping at first but I paused and was able to crash it at the same point by positioning to know missing segments.  skipping to EOF seems ok so playing "live" after failure does continue;

However spam is worse there are now two values logged

```
2020-07-14 15:09:19.832 T:3040    DEBUG <CAddonSettings[inputstream.ffmpegdirect]>: loading setting definitions
2020-07-14 15:09:19.836 T:3040    DEBUG <CAddonSettings[inputstream.ffmpegdirect]>: loading setting values
```

**Comment by phunkyfish** [comment] 2020-07-14 19:31
Ok, so only a crash when skipping after pause?

Are you sure the log spam is worse? There should only be 2 statements per stream and not continuous.

**Comment by emveepee** [comment] 2020-07-14 20:20
I think the problem was my self debug compile.  The spam is gone, sorry about that.  

The behaviour for skipping is a little different.  If I skip to dead area it will freeze playback but I can skip out of it to the live buffer.  

For pause there seems to be Kodi memory buffering separate from the seg files since I can skip and play forward after a long pause.  My Kodi memory does increase while paused too and it jumps back down on exit.

**Comment by phunkyfish** [comment] 2020-07-14 21:14
> The behaviour for skipping is a little different. If I skip to dead area it will freeze playback but I can skip out of it to the live buffer.

This is by design. If no real packets can be found empty packets will be returned instead. As this would only occur when disk space is exhausted I think this is probably ok.

> For pause there seems to be Kodi memory buffering separate from the seg files since I can skip and play forward after a long pause. My Kodi memory does increase while paused too and it jumps back down on exit.

Yes, remember this is all designed around there being available disk space. If you have none then memory will be used. However once you restore the disk space it should function as normal again. 

So do you think this is good to merge?

**Comment by emveepee** [comment] 2020-07-14 23:22
It is fine for me.  Maybe you should address the orginal credentials issue too , since I think it is up to the addon and it isn't too hard.

```C++
#include "url/URL.h"
...
        Log(LOGLEVEL_ERROR, "%s - Failed to open segment file on disk: %s, disk free space (MB): %lld", __FUNCTION__, CURL(m_timeshiftSegmentFilePath).GetWithoutUserDetails(true).c_str(), static_cast<long long>(freeSpaceMB));
```
Just because other addons don't follow doesn't mean you need to add a new leak.

**Comment by puenktchen** [comment] 2020-07-15 01:01
One minor thing. Why are you doing this:
https://github.com/xbmc/inputstream.ffmpegdirect/blob/99b42738d6efacc559ebc5963ec6e8f995b263fc/src/stream/TimeshiftBuffer.cpp#L24
This of course creates an error in the log if the timeshift path is the share itself. But even when it's just an ordinary folder it shouldn't be needed because of this: https://alwinesch.github.io/group__cpp__kodi__vfs___c_file.html#ga791aab50c47c2f6420a90b943e39683d

> Related folders becomes created if not present.

Or am i wrong?

**Comment by phunkyfish** [comment] 2020-07-15 07:28
> It is fine for me. Maybe you should address the orginal credentials issue too , since I think it is up to the addon and it isn't too hard.
> 
> ```c++
> #include "url/URL.h"
> ...
>         Log(LOGLEVEL_ERROR, "%s - Failed to open segment file on disk: %s, disk free space (MB): %lld", __FUNCTION__, CURL(m_timeshiftSegmentFilePath).GetWithoutUserDetails(true).c_str(), static_cast<long long>(freeSpaceMB));
> ```
> 
> Just because other addons don't follow doesn't mean you need to add a new leak.

Ah, yes, thanks for reminding me, I actually have this on another branch. Will add it today. It actually occurs in way more places than just the timeshift code.

**Comment by phunkyfish** [comment] 2020-07-15 07:34
> https://alwinesch.github.io/group__cpp__kodi__vfs___c_file.html#ga791aab50c47c2f6420a90b943e39683d

Fair point, but it might be more intuitive to only create the directory if it doesn't exist. I will add that too.

**Comment by phunkyfish** [comment] 2020-07-15 11:12
Ok, testbuilds: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.ffmpegdirect/detail/PR-59/8/artifacts

That should be everything.

**Comment by emveepee** [comment] 2020-07-15 13:40
> 
> 
> Ok, testbuilds: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.ffmpegdirect/detail/PR-59/8/artifacts
> 
> That should be everything.

LGTM

**Comment by puenktchen** [comment] 2020-07-15 18:18
It also fine for me.
Have you incorporated also this: https://github.com/xbmc/inputstream.ffmpegdirect/issues/60#issuecomment-654517752
because i don't get any file left overs anymore. So my other issue can also be closed.
Thank you both!

**Comment by phunkyfish** [comment] 2020-07-15 18:31
Yes. Also included.

**Closed as completed** 2020-07-17 11:21 UTC
